from .user import MyUserCreationForm, MyUserChangeForm
from .creator import MyCreatorCreationForm, MyCreatorChangeForm, CreatorSkillCreationForm, CreatorSkillChangeForm
from .classes import MyCreatorClassCreationForm, MyCreatorClassChangeForm, ClassKeywordCreationForm, ClassKeywordChangeForm, ClassCoversCreationForm, ClassCoversChangeForm, ClassMaterialCreationForm, ClassMaterialChangeForm
from .reviews import MyCreatorReviewCreationForm, MyCreatorReviewChangeForm, MyClassReviewCreationForm, MyClassReviewChangeForm
from .materials import MyMaterialCategoryCreationForm, MyMaterialCategoryChangeForm, MyMaterialCreationForm, MyMaterialChangeForm
from .testimonials import TestimonialCreationForm, TestimonialChangeForm
from .onetoonesession import OneToOneSessionCreationForm, OneToOneSessionChangeForm, TimeSlotCreationForm, TimeSlotChangeForm
from .keywords import AdminKeywordCreationForm, AdminKeywordChangeForm
from .plans import PlanCreationForm, PlanChangeForm, PlanCoverCreationForm, PlanCoverChangeForm