# Generated by Django 3.1.2 on 2020-11-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration_in_months',
            field=models.CharField(blank=True, default='1', max_length=2, null=True),
        ),
    ]
