# Generated by Django 3.1.2 on 2021-01-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorClassCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('affiliation_deduction', models.PositiveIntegerField(blank=True, default=10, null=True)),
                ('creator_class_deduction', models.PositiveIntegerField(blank=True, default=10, null=True)),
            ],
            options={
                'verbose_name': 'Creator Classes Commission',
                'verbose_name_plural': 'Creator Classes Commission',
                'ordering': ['-created_at'],
            },
        ),
    ]
