# Generated by Django 3.1.2 on 2021-04-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_auto_20210225_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminkeyword',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='keyword/'),
        ),
    ]
