# Generated by Django 3.1.2 on 2021-04-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0005_adminkeyword_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminkeyword',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='keyword/'),
        ),
    ]
