# Generated by Django 3.1.2 on 2021-04-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0006_auto_20210416_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminkeyword',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='keyword/'),
        ),
    ]
