# Generated by Django 3.1.2 on 2021-04-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_auto_20210419_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminkeyword',
            name='image',
            field=models.ImageField(default='', upload_to='keyword/'),
            preserve_default=False,
        ),
    ]
