# Generated by Django 3.1.2 on 2021-04-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0008_auto_20210427_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminkeyword',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='keyword/'),
        ),
    ]
