# Generated by Django 3.1.2 on 2021-04-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0009_auto_20210430_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminkeyword',
            name='image',
            field=models.ImageField(default='', upload_to='keyword/'),
            preserve_default=False,
        ),
    ]
