# Generated by Django 3.1.2 on 2021-05-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0010_auto_20210430_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='discount_amount',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
