# Generated by Django 3.1.2 on 2021-05-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0011_plan_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
