# Generated by Django 3.1.2 on 2020-11-03 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CreatorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('review', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('rating', models.FloatField(blank=True, default=1, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_for_creator', to='creator.creator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator Review',
                'verbose_name_plural': 'Creator reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
