# Generated by Django 3.1.2 on 2020-11-04 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_classcovers_classkeyword_creatorclass'),
        ('user', '0003_auto_20201104_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_creator', to='creator.creator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favourite Creator',
                'verbose_name_plural': 'Favourite Creators',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavouriteClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('creator_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_class', to='creator.creatorclass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favourite Class',
                'verbose_name_plural': 'Favourite Classes',
                'ordering': ['-created_at'],
            },
        ),
    ]
