# Generated by Django 3.1.2 on 2020-12-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Customer Id'),
        ),
    ]
