# Generated by Django 3.1.2 on 2020-12-23 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionbooking',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_session_payment', to='user.card'),
        ),
        migrations.AlterField(
            model_name='streambooking',
            name='user_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stream_payment', to='user.card'),
        ),
    ]
