# Generated by Django 3.1.2 on 2020-12-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201223_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionbooking',
            name='user_card',
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='card_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
