# Generated by Django 3.1.2 on 2020-12-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
        ('user', '0011_auto_20201223_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='customadmin.AdminKeyword'),
        ),
    ]
