# Generated by Django 3.1.2 on 2020-12-28 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_sessionbooking_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streambooking',
            name='user_card',
        ),
        migrations.AddField(
            model_name='streambooking',
            name='card_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streambooking',
            name='transaction_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.transactiondetail'),
        ),
    ]
