# Generated by Django 3.1.2 on 2020-12-28 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
        ('user', '0014_auto_20201228_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_for_creator', to='customadmin.plan'),
        ),
        migrations.AddField(
            model_name='user',
            name='plan_purchased_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
