# Generated by Django 3.1.2 on 2020-12-29 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
        ('user', '0015_auto_20201228_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_purchase_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_payment_detail', to='user.transactiondetail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_plan', to='customadmin.plan'),
        ),
    ]
