# Generated by Django 3.1.2 on 2020-12-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20201229_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='amount',
            field=models.FloatField(blank=True, max_length=255, null=True, verbose_name='Amount'),
        ),
    ]
