# Generated by Django 3.1.2 on 2021-01-01 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_stripe_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('title', models.CharField(blank=True, help_text='Notification Title', max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Notification Description', null=True, verbose_name='Description')),
                ('is_read', models.BooleanField(default=False, help_text='Is Notification Read?', verbose_name='Is Notification Read?')),
                ('notification_type', models.CharField(blank=True, choices=[('OTHER', 'OTHER'), ('BOOKING', 'BOOKING')], help_text='Notification Title', max_length=255, null=True, verbose_name='Title')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
