# Generated by Django 3.1.2 on 2021-01-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Notification Title', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
