# Generated by Django 3.1.2 on 2021-01-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210101_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brand',
            field=models.CharField(blank=True, max_length=255, verbose_name='Brand of card'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Card Id'),
        ),
        migrations.AddField(
            model_name='user',
            name='card_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Card holder name'),
        ),
        migrations.AddField(
            model_name='user',
            name='exp_month',
            field=models.CharField(blank=True, max_length=255, verbose_name='Exp. month'),
        ),
        migrations.AddField(
            model_name='user',
            name='exp_year',
            field=models.CharField(blank=True, max_length=255, verbose_name='Exp. year'),
        ),
        migrations.AddField(
            model_name='user',
            name='last4',
            field=models.CharField(blank=True, max_length=255, verbose_name='Last 4 digits'),
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
