# Generated by Django 3.1.2 on 2021-01-13 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_creator_affiliation_link'),
        ('user', '0021_auto_20210105_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliated_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='creator.creator'),
        ),
    ]
