# Generated by Django 3.1.2 on 2021-01-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_user_affiliated_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='profile_image',
            field=models.ImageField(blank=True, default='sample.jpg', null=True, upload_to='profile_image', verbose_name='Profile Image'),
        ),
    ]
