# Generated by Django 3.1.2 on 2021-01-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_notification_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='link_expired_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
