# Generated by Django 3.1.2 on 2021-01-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_user_link_expired_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_link',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
