# Generated by Django 3.1.2 on 2021-02-10 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_creatorclasscommission'),
        ('user', '0025_user_password_reset_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSelectedKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('keywords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selected_keyword', to='customadmin.adminkeyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Selected Keyword',
                'verbose_name_plural': 'User Selected Keywords',
                'ordering': ['-created_at'],
            },
        ),
    ]
