# Generated by Django 3.1.2 on 2021-02-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_userselectedkeyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userselectedkeyword',
            old_name='keywords',
            new_name='keyword',
        ),
    ]
