# Generated by Django 3.1.2 on 2021-02-12 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_creatorclasscommission'),
        ('user', '0027_auto_20210211_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlanPurchaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to='customadmin.plan')),
                ('plan_purchase_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_detail', to='user.transactiondetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Purchase History',
                'verbose_name_plural': 'Plan Purchase History',
                'ordering': ['-created_at'],
            },
        ),
    ]
