# Generated by Django 3.1.2 on 2021-02-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_userplanpurchasehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='captured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='paid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='refunds_has_more',
            field=models.BooleanField(default=False),
        ),
    ]
