# Generated by Django 3.1.2 on 2021-02-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20210225_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetail',
            name='metadata',
            field=models.CharField(blank=True, max_length=855, null=True, verbose_name='Metadata'),
        ),
    ]
