# Generated by Django 3.1.2 on 2021-03-15 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0004_auto_20210225_0911'),
        ('user', '0031_auto_20210225_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_selected_keywords', to='customadmin.adminkeyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_keyword', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Keyword',
                'verbose_name_plural': 'User Keywords',
                'ordering': ['-created_at'],
            },
        ),
    ]
