# Generated by Django 3.1.2 on 2021-03-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_userkeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='agora_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='agora_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sessionbooking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streambooking',
            name='agora_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streambooking',
            name='agora_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streambooking',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='streambooking',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
