# Generated by Django 3.1.2 on 2021-03-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20210315_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionbooking',
            name='agora_token',
        ),
        migrations.RemoveField(
            model_name='sessionbooking',
            name='agora_uid',
        ),
        migrations.RemoveField(
            model_name='sessionbooking',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='sessionbooking',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='streambooking',
            name='agora_token',
        ),
        migrations.RemoveField(
            model_name='streambooking',
            name='agora_uid',
        ),
        migrations.RemoveField(
            model_name='streambooking',
            name='channel_name',
        ),
        migrations.RemoveField(
            model_name='streambooking',
            name='completed',
        ),
    ]
