# Generated by Django 3.1.2 on 2021-03-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20210316_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionbooking',
            name='user_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='streambooking',
            name='user_joined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='creatorreview',
            name='rating',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
    ]
