# Generated by Django 3.1.2 on 2021-03-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20210318_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='streambooking',
            name='user_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
