# Generated by Django 3.1.2 on 2021-04-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_streambooking_user_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='streambooking',
            name='host',
            field=models.BooleanField(default=False),
        ),
    ]
