# Generated by Django 3.1.2 on 2021-04-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0007_auto_20210419_1536'),
        ('creator', '0019_stream_screen_share'),
        ('user', '0037_streambooking_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_stream', to='creator.stream'),
        ),
        migrations.AddField(
            model_name='streambooking',
            name='keywords',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_booking', to='customadmin.adminkeyword'),
        ),
    ]
