# Generated by Django 3.1.2 on 2021-04-24 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20210421_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_flag', models.ImageField(blank=True, null=True, upload_to='country/')),
            ],
            options={
                'verbose_name': 'CountryField',
                'verbose_name_plural': 'CountryFields',
                'ordering': ['country_name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='country_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.countryfield'),
        ),
    ]
