# Generated by Django 3.1.2 on 2021-04-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20210424_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='countryfield',
            options={'ordering': ['country_name'], 'verbose_name': 'Country Field', 'verbose_name_plural': 'Country Fields'},
        ),
    ]
