# Generated by Django 3.1.2 on 2021-04-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20210427_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryfield',
            name='country_flag',
            field=models.ImageField(default='India', upload_to='country/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='countryfield',
            name='country_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
