# Generated by Django 3.1.2 on 2021-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20210427_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag_login',
            field=models.BooleanField(default=False),
        ),
    ]
