# Generated by Django 3.1.2 on 2021-06-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0013_plan_stripe_product_id'),
        ('creator', '0031_auto_20210603_1221'),
        ('user', '0043_auto_20210504_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='affiliated_with',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='creator.creator'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.countryfield'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_plan', to='customadmin.plan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan_purchase_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_payment_detail', to='user.transactiondetail'),
        ),
    ]
