# Generated by Django 3.1.2 on 2021-06-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_auto_20210603_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplanpurchasehistory',
            name='status',
            field=models.CharField(blank=True, default='canceled', max_length=50, null=True),
        ),
    ]
