# Generated by Django 3.1.2 on 2020-11-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('thumbnail_file', models.FileField(blank=True, null=True, upload_to='class_content', verbose_name='class thumbnail')),
                ('class_file', models.FileField(blank=True, null=True, upload_to='class_content', verbose_name='Class video')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_by', to='creator.creator')),
            ],
            options={
                'verbose_name': 'Creator Class',
                'verbose_name_plural': 'Creator Classes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('keyword', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('creator_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_for', to='creator.creatorclass')),
            ],
            options={
                'verbose_name': 'Class Keyword',
                'verbose_name_plural': 'Class Keywords',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassCovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('covers', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('creator_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.creatorclass')),
            ],
            options={
                'verbose_name': 'Class Cover',
                'verbose_name_plural': 'Class Covers',
                'ordering': ['-created_at'],
            },
        ),
    ]
