# Generated by Django 3.1.2 on 2020-11-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_classcovers_classkeyword_creatorclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('category_title', models.CharField(blank=True, default='', max_length=40, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='material_category', verbose_name='category image')),
            ],
            options={
                'verbose_name': 'Material Category',
                'verbose_name_plural': 'Material Categories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('title', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('thumbnail_file', models.FileField(blank=True, null=True, upload_to='materials', verbose_name='material thumbnail')),
                ('material_file', models.FileField(blank=True, null=True, upload_to='materials', verbose_name='material file')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_creator', to='creator.creator')),
                ('material_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_category', to='creator.materialcategory')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
