# Generated by Django 3.1.2 on 2020-11-09 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_adminkeyword'),
        ('creator', '0003_material_materialcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classkeyword',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.adminkeyword'),
        ),
        migrations.CreateModel(
            name='ClassMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('class_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.material')),
                ('creator_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.creatorclass')),
            ],
            options={
                'verbose_name': 'Class material',
                'verbose_name_plural': 'Class materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
