# Generated by Django 3.1.2 on 2020-11-20 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_auto_20201117_1013'),
        ('creator', '0003_material_materialcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOneSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('amount', models.FloatField(blank=True, default=50, null=True)),
            ],
            options={
                'verbose_name': 'Creator OneToOne Session',
                'verbose_name_plural': 'Creator OneToOne Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('title', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('thumbnail_file', models.FileField(blank=True, null=True, upload_to='stream', verbose_name='Stream thumbnail')),
                ('sneak_peak_file', models.FileField(blank=True, null=True, upload_to='stream', verbose_name='Stream sneak peak')),
                ('stream_datetime', models.DateField(blank=True, help_text='Stream Datetime', null=True, verbose_name='Stream Datetime')),
                ('stream_amount', models.FloatField(blank=True, default=10, null=True)),
                ('total_seats', models.IntegerField(blank=True, default=10, null=True)),
            ],
            options={
                'verbose_name': 'Creator Stream',
                'verbose_name_plural': 'Creator Streams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='creator',
            name='status',
            field=models.CharField(choices=[('REJECT', 'Rejected'), ('PENDING', 'Pending'), ('ACCEPT', 'Accepted')], default='PENDING', max_length=7),
        ),
        migrations.AlterField(
            model_name='classkeyword',
            name='keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.adminkeyword'),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('slot_datetime', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessiontimeslot', to='creator.onetoonesession')),
            ],
            options={
                'verbose_name': 'OneToOne Session Time Slot',
                'verbose_name_plural': 'OneToOne Session Time Slots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('keyword', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customadmin.adminkeyword')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_keywords', to='creator.stream')),
            ],
            options={
                'verbose_name': 'Stream Keyword',
                'verbose_name_plural': 'Stream Keywords',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StreamCovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('covers', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.stream')),
            ],
            options={
                'verbose_name': 'Stream Cover',
                'verbose_name_plural': 'Stream Covers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stream',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_by', to='creator.creator'),
        ),
        migrations.AddField(
            model_name='onetoonesession',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessioncreator', to='creator.creator'),
        ),
        migrations.CreateModel(
            name='ClassMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('class_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.material')),
                ('creator_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creator.creatorclass')),
            ],
            options={
                'verbose_name': 'Class material',
                'verbose_name_plural': 'Class materials',
                'ordering': ['-created_at'],
            },
        ),
    ]
