# Generated by Django 3.1.2 on 2020-11-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_auto_20201109_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOneSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('amount', models.FloatField(blank=True, default=50, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessioncreator', to='creator.creator')),
            ],
            options={
                'verbose_name': 'Creator OneToOne Session',
                'verbose_name_plural': 'Creator OneToOne Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('slot_datetime', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessiontimeslot', to='creator.onetoonesession')),
            ],
            options={
                'verbose_name': 'OneToOne Session Time Slot',
                'verbose_name_plural': 'OneToOne Session Time Slots',
                'ordering': ['-created_at'],
            },
        ),
    ]
