# Generated by Django 3.1.2 on 2020-12-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_auto_20201126_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='creator_website_url',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
