# Generated by Django 3.1.2 on 2020-11-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_auto_20201120_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='stream_datetime',
            field=models.DateTimeField(blank=True, help_text='Stream Datetime', null=True, verbose_name='Stream Datetime'),
        ),
    ]
