# Generated by Django 3.1.2 on 2021-01-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_creator_creator_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='affiliation_link',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
