# Generated by Django 3.1.2 on 2021-01-18 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creator', '0006_creator_affiliation_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorAffiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='customadmin.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Creator Affiliation',
                'verbose_name_plural': 'Creator Affiliation',
                'ordering': ['-created_at'],
            },
        ),
    ]
