# Generated by Django 3.1.2 on 2021-01-19 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_creatoraffiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatorTransferredMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('total_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('admin_amount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(blank=True, choices=[('success', 'Success'), ('fail', 'Fail')], default='fail', max_length=222, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=222, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to='creator.creator')),
            ],
            options={
                'verbose_name': 'Creator Transferred Money',
                'verbose_name_plural': 'Creator Transferred Money',
            },
        ),
    ]
