# Generated by Django 3.1.2 on 2021-01-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_creatortransferredmoney'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatortransferredmoney',
            old_name='admin_amount',
            new_name='affiliation_commission_total',
        ),
        migrations.RenameField(
            model_name='creatortransferredmoney',
            old_name='total_amount',
            new_name='affiliation_deduction',
        ),
        migrations.RenameField(
            model_name='creatortransferredmoney',
            old_name='transfer_amount',
            new_name='creator_class_deduction',
        ),
        migrations.AddField(
            model_name='creatoraffiliation',
            name='admin_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='creatoraffiliation',
            name='transfer_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='creatortransferredmoney',
            name='creator_earnings',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='creatortransferredmoney',
            name='final_commission_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='creatortransferredmoney',
            name='final_earning_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='creatortransferredmoney',
            name='transferred_amount',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
