# Generated by Django 3.1.2 on 2021-01-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_auto_20210119_0640'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date when created.', null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date when updated.', null=True, verbose_name='Updated At')),
                ('error_text', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name': 'Payout Error Log',
                'verbose_name_plural': 'Payout Error Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
