# Generated by Django 3.1.2 on 2021-01-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0010_payouterrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorclass',
            name='promo_file',
            field=models.FileField(blank=True, null=True, upload_to='class_content', verbose_name='Class promo'),
        ),
    ]
