# Generated by Django 3.1.2 on 2021-02-11 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0011_creatorclass_promo_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creatoraffiliation',
            old_name='admin_amount',
            new_name='commission_amount',
        ),
    ]
