# Generated by Django 3.1.2 on 2021-02-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0012_auto_20210211_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatortransferredmoney',
            name='session_amount_received',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='creatortransferredmoney',
            name='session_amount_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='creatortransferredmoney',
            name='stream_amount_received',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='creatortransferredmoney',
            name='stream_amount_total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
