# Generated by Django 3.1.2 on 2021-02-15 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0003_availabletimezone'),
        ('creator', '0013_auto_20210212_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='tz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_timezones', to='customadmin.availabletimezone'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='tz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_timezones', to='customadmin.availabletimezone'),
        ),
    ]
