# Generated by Django 3.1.2 on 2021-03-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0015_auto_20210316_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslot',
            name='screen_share',
            field=models.BooleanField(default=False),
        ),
    ]
