# Generated by Django 3.1.2 on 2021-03-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0016_timeslot_screen_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='stream_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='session_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
