# Generated by Django 3.1.2 on 2021-03-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0017_auto_20210316_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorclass',
            name='class_file',
            field=models.FileField(blank=True, null=True, upload_to='class_content', verbose_name='Class file'),
        ),
    ]
