# Generated by Django 3.1.2 on 2021-03-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0018_auto_20210318_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='screen_share',
            field=models.BooleanField(default=False),
        ),
    ]
