# Generated by Django 3.1.2 on 2021-05-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0020_creatorclass_class_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creator',
            old_name='google_url',
            new_name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='twitter_url',
        ),
    ]
