# Generated by Django 3.1.2 on 2021-05-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0021_auto_20210503_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='affiliation_link',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='creator_website_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='facebook_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='instagram_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='youtube_url',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
