# Generated by Django 3.1.2 on 2021-05-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0022_auto_20210503_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='affiliation_link',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
