# Generated by Django 3.1.2 on 2021-05-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0023_auto_20210504_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorclass',
            name='class_file_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Class file URL'),
        ),
        migrations.AddField(
            model_name='material',
            name='material_file_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='material file url'),
        ),
        migrations.AddField(
            model_name='stream',
            name='sneak_peak_file_url',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Stream sneak peak URL'),
        ),
    ]
