# Generated by Django 3.1.2 on 2021-05-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0024_auto_20210505_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creatorclass',
            name='class_file_url',
        ),
        migrations.RemoveField(
            model_name='material',
            name='material_file_url',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='sneak_peak_file_url',
        ),
        migrations.AlterField(
            model_name='creatorclass',
            name='promo_file',
            field=models.FileField(blank=True, null=True, upload_to='public/classes', verbose_name='Class promo'),
        ),
        migrations.AlterField(
            model_name='creatorclass',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to='public/classes', verbose_name='class thumbnail'),
        ),
        migrations.AlterField(
            model_name='material',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to='public/materials', verbose_name='material thumbnail'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='sneak_peak_file',
            field=models.FileField(blank=True, null=True, upload_to='public/stream', verbose_name='Stream sneak peak'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to='public/stream', verbose_name='Stream thumbnail'),
        ),
    ]
