# Generated by Django 3.1.2 on 2021-05-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0025_auto_20210505_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatorclass',
            name='class_file',
            field=models.FileField(blank=True, null=True, upload_to='public/classes', verbose_name='Class file'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to='public/materials', verbose_name='material file'),
        ),
    ]
