# Generated by Django 3.1.2 on 2021-05-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0026_auto_20210505_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='screen_share_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
