# Generated by Django 3.1.2 on 2021-05-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0027_stream_screen_share_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorclass',
            name='transcoded_class_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
