# Generated by Django 3.1.2 on 2021-05-28 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0028_creatorclass_transcoded_class_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='transcoded_material_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='transcoded_sneak_peak_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
