# Generated by Django 3.1.2 on 2021-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0029_auto_20210528_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='sneak_peak_file',
            field=models.FileField(blank=True, null=True, upload_to='public/streams', verbose_name='Stream sneak peak'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='thumbnail_file',
            field=models.FileField(blank=True, null=True, upload_to='public/streams', verbose_name='Stream thumbnail'),
        ),
    ]
