# Generated by Django 3.1.2 on 2021-06-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0030_auto_20210529_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creatoraffiliation',
            name='commission_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='creatoraffiliation',
            name='transfer_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
